### ISSUE TITLE
Lägga till möjlighet att skicka ut custom commands privat endast för dig

### ISSUE THREAD

**Issue by liamvendel** [KonkenBonken/KonkenBoten#114]

**Comment by KonkenBonken** [comment]
Todo:
Add `private` option to
- [ ] All Custom Commands
- [ ] /echo
- [ ] /userinfo
- [ ] /roleinfo
- [ ] /serverinfo

**Comment by KonkenBonken** [comment]
Utöver #116 så bidrar även 21fba969cba95354fbb4b7e6d4340db2ec7c1043 till detta
