### ISSUE TITLE
"Joined server" och "Joined Discord" rutorna får alltid samma tid som när meddelandet skickas ut när !userinfo används

### ISSUE THREAD

**Issue by liamvendel** [KonkenBonken/KonkenBoten#118]
![unknown](https://user-images.githubusercontent.com/82840663/177006808-ea5c8adf-f03a-4de8-a8cc-27742ee65942.png)

**Comment by KonkenBonken** [comment]
Väldigt konstigt
Som du ser [här](https://github.com/KonkenBonken/KonkenBoten/blob/master/script.js#L4217-L4218) så ser det ut som att det bör fungera som det ska.
Får undersöka saken

**Comment by KonkenBonken** [comment]
This is a bug on [line 2856 in script.js](https://github.com/KonkenBonken/KonkenBoten/blob/6d887d776ed8ebdea5f546795cadd56f4ce4d0b6/script.js#L2856) that was introduced in 075d777cc257e54d3d7df101286a7806f2fb1218 that implemented different time zones depending on the server's locale

**Comment by KonkenBonken** [comment]
Oops, den commit:en ska inte vara med här
Men verkar inte gå o radera...
