### ISSUE TITLE
Lägg till mer info på !serverinfo kommandot

### ISSUE THREAD

**Issue by liamvendel** [KonkenBonken/KonkenBoten#81]
- antal kategorier
- antal medlemmar online
- antal bottar

**Comment by KonkenBonken** [comment]
- **Antal kategorier**
- **Antal medlemmar online**
  - Nekad pga att botten inte har tillgång till medlemmars onlinestatus i nuläget
- **Antal bottar**

**Comment by KonkenBonken** [comment]
Fixat i 9ebab47187fd6da2a6305d2dea3aa5fc054f8e20
