### ISSUE TITLE
Automod

### ISSUE THREAD

**Issue by liamvendel** [KonkenBonken/KonkenBoten#93]
- [x] Caps
- [x] Word
- [x] Link
- [x] Mentions
- [x] Zalgo
- [x] Invite
- [x] Spam
- [ ] Emoji

**Comment by KonkenBonken** [comment]
Feature was added in
- 653b2bd2f4e4f29ccfe7ce0db7b89f30f32bb11c
- 0c199f1d902a28b4725b963215365f66611035af
- 514ae0a33dc4254d8d330eadd0d3ad90197d9b8e
- 729d1113fa154b84a892bd7760fbbf19fdd0a4ba
- 9c250fc9de89c7fea08d585790923653bc56a576
